Feature/readme
Byndyusoft/Byndyusoft.ApiClient pull request #6
Opened 2023-08-09 07:15 UTC by asyaflesh

2023-08-09 13:36 UTC, Satem commented
Very good. The only suggestion that I can make is to change "make it derived" to "declare it as derived" and "to include" to "to register".

2023-08-10 05:07 UTC, Rinatich requested changes

2023-08-10 05:07 UTC, Rinatich commented on README.md
> +2. Great! Now you can use the predefined methods to describe your HTTP requests:
describe => declare. Могу ошибаться, может, Коля поправит.
Describe - это больше про объяснение чего-то.
Я бы написал как _declare your API methods_.

2023-08-10 05:07 UTC, Rinatich commented on README.md
> +3.  Make sure to register your client wherever you need to use it:
Чуть сложновато читается )) можно и так оставить, но я бы хотя бы сделал 
_Make sure to register your client wherever you need it_

2023-08-10 07:11 UTC, Satem commented on README.md
> +2. Great! Now you can use the predefined methods to describe your HTTP requests:
Может, проще всего сказать "declare your methods". В случае "API methods" я бы подумал, что это те методы, которые принимают запросы - методы контроллера, например.

2023-08-10 08:58 UTC, asyaflesh commented on README.md
> +# API client creation library  [![Nuget](https://img.shields.io/nuget/v/Byndyusoft.ApiClient.svg)](https://www.nuget.org/packages/Byndyusoft.ApiClient/) [![Downloads](https://img.shields.io/nuget/dt/
Согласна, пусть будет разделение названия и описания

2023-08-10 08:59 UTC, asyaflesh commented on README.md
> +* GetAsync - used for retrieving (reading)
Согласна, рябит в глазах

2023-08-10 09:25 UTC, asyaflesh commented on README.md
> +# API client creation library  [![Nuget](https://img.shields.io/nuget/v/Byndyusoft.ApiClient.svg)](https://www.nuget.org/packages/Byndyusoft.ApiClient/) [![Downloads](https://img.shields.io/nuget/dt/
Не стала добавлять как будто и так очевидно, плюс в описании методов есть http

2023-08-10 09:34 UTC, Rinatich approved these changes

2023-08-10 10:09 UTC, merged